-- サブウェイ・ゲッサー日本版: jp_profiles, jp_plays and all-time rankings.
create table if not exists public.jp_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null unique check (char_length(nickname) between 1 and 12),
  theme_line text not null default 'G' check (theme_line in ('G','M','H','T','C','Y','Z','N','F','A','I','S','E')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.jp_profiles enable row level security;
drop policy if exists jp_profiles_read_all on public.jp_profiles;
drop policy if exists jp_profiles_insert_own on public.jp_profiles;
drop policy if exists jp_profiles_update_own on public.jp_profiles;
create policy jp_profiles_read_all on public.jp_profiles for select using (true);
create policy jp_profiles_insert_own on public.jp_profiles for insert with check (auth.uid() = id);
create policy jp_profiles_update_own on public.jp_profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create table if not exists public.jp_plays (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  score integer not null check (score between 0 and 216),
  region text not null default 'tokyo' check (region = 'tokyo'),
  mode text not null default 'all' check (mode = 'all'),
  rank_mode text not null default 'tokyo:all' check (rank_mode = 'tokyo:all'),
  mode_label text not null default '東京 地下鉄全13路線',
  duration_sec integer not null check (duration_sec in (60, 120, 300)),
  theoretical_max integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists jp_plays_ranking_idx
  on public.jp_plays (rank_mode, duration_sec, user_id, score desc, created_at);
create index if not exists jp_plays_user_history_idx on public.jp_plays (user_id, created_at desc);

alter table public.jp_plays enable row level security;
drop policy if exists jp_plays_read_own on public.jp_plays;
drop policy if exists jp_plays_insert_own on public.jp_plays;
create policy jp_plays_read_own on public.jp_plays for select using (auth.uid() = user_id);
create policy jp_plays_insert_own on public.jp_plays for insert with check (auth.uid() = user_id);

create or replace function public.jp_tokyo_theoretical_max(p_duration integer)
returns integer language sql immutable set search_path = '' as $$
  select least(216, ceil(greatest(coalesce(p_duration, 60), 1) * 1000.0 / 500.0)::integer);
$$;

create or replace function public.jp_normalize_tokyo_play()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if auth.uid() is null or new.user_id <> auth.uid() then
    raise exception 'invalid user' using errcode = '42501';
  end if;
  new.region := 'tokyo';
  new.mode := 'all';
  new.rank_mode := 'tokyo:all';
  new.duration_sec := case when new.duration_sec in (60,120,300) then new.duration_sec else 60 end;
  new.theoretical_max := public.jp_tokyo_theoretical_max(new.duration_sec);
  new.score := greatest(0, least(new.score, new.theoretical_max));
  return new;
end;
$$;

drop trigger if exists jp_normalize_tokyo_play_trigger on public.jp_plays;
create trigger jp_normalize_tokyo_play_trigger before insert or update on public.jp_plays
for each row execute function public.jp_normalize_tokyo_play();

revoke all on function public.jp_normalize_tokyo_play() from public;

drop function if exists public.jp_all_time_ranking_by_duration(text, integer, integer);
create function public.jp_all_time_ranking_by_duration(
  p_mode text,
  p_duration integer,
  p_limit integer default 100
)
returns table (
  rank bigint,
  user_id uuid,
  nickname text,
  theme_line text,
  best_score bigint,
  theoretical_max bigint,
  record_points numeric,
  percentile_bonus numeric,
  adjusted_score numeric
)
language sql stable security definer set search_path = '' as $$
  with best as (
    select p.user_id, max(p.score)::bigint as best_score
    from public.jp_plays p
    where p.rank_mode = 'tokyo:all'
      and p.duration_sec = case when p_duration in (60,120,300) then p_duration else 60 end
    group by p.user_id
  ), calculated as (
    select b.user_id, b.best_score,
      public.jp_tokyo_theoretical_max(p_duration)::bigint as theoretical_max,
      round((70 * sqrt(b.best_score::numeric / public.jp_tokyo_theoretical_max(p_duration)))::numeric, 1) as record_points,
      count(*) over ()::bigint as participant_count,
      rank() over (order by b.best_score desc)::bigint as score_rank
    from best b
  ), scored as (
    select c.*,
      round((case when c.participant_count <= 1 then 30
        else 30 * (c.participant_count - c.score_rank)::numeric / (c.participant_count - 1) end)::numeric, 1) as percentile_bonus
    from calculated c
  ), ordered as (
    select rank() over (
      order by (s.record_points + s.percentile_bonus) desc
    )::bigint as final_rank, s.*
    from scored s
  )
  select o.final_rank, o.user_id,
    coalesce(pr.nickname, '匿名プレイヤー')::text,
    coalesce(pr.theme_line, 'G')::text,
    o.best_score, o.theoretical_max, o.record_points, o.percentile_bonus,
    round((o.record_points + o.percentile_bonus)::numeric, 1) as adjusted_score
  from ordered o
  left join public.jp_profiles pr on pr.id = o.user_id
  where o.final_rank <= least(greatest(coalesce(p_limit, 100), 1), 100)
  order by o.final_rank, o.best_score desc, o.user_id;
$$;

revoke all on function public.jp_all_time_ranking_by_duration(text, integer, integer) from public;
grant execute on function public.jp_all_time_ranking_by_duration(text, integer, integer) to anon, authenticated;
grant select, insert on public.jp_profiles to authenticated;
grant update (nickname, theme_line, updated_at) on public.jp_profiles to authenticated;
grant select, insert on public.jp_plays to authenticated;
grant usage, select on sequence public.jp_plays_id_seq to authenticated;
