-- サブウェイ・ゲッサー日本版 / Supabase fresh install
-- Supabase SQL Editorでこのファイル全体を1回実行してください。
-- Generated by scripts/build-supabase-schema.mjs. Edit source fragments instead.

-- サブウェイ・ゲッサー日本版: accounts, plays and all-time rankings.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null unique check (char_length(nickname) between 1 and 12),
  theme_line text not null default 'G' check (theme_line in ('G','M','H','T','C','Y','Z','N','F','A','I','S','E')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
drop policy if exists profiles_read_all on public.profiles;
drop policy if exists profiles_insert_own on public.profiles;
drop policy if exists profiles_update_own on public.profiles;
create policy profiles_read_all on public.profiles for select using (true);
create policy profiles_insert_own on public.profiles for insert with check (auth.uid() = id);
create policy profiles_update_own on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create table if not exists public.plays (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  score integer not null check (score between 0 and 216),
  region text not null default 'tokyo' check (region = 'tokyo'),
  mode text not null default 'all' check (mode = 'all'),
  rank_mode text not null default 'tokyo:all' check (rank_mode = 'tokyo:all'),
  mode_label text not null default '東京 地下鉄全13路線',
  duration_sec integer not null check (duration_sec in (60, 120, 300)),
  theoretical_max integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists plays_ranking_idx
  on public.plays (rank_mode, duration_sec, user_id, score desc, created_at);
create index if not exists plays_user_history_idx on public.plays (user_id, created_at desc);

alter table public.plays enable row level security;
drop policy if exists plays_read_own on public.plays;
drop policy if exists plays_insert_own on public.plays;
create policy plays_read_own on public.plays for select using (auth.uid() = user_id);
create policy plays_insert_own on public.plays for insert with check (auth.uid() = user_id);

create or replace function public.tokyo_theoretical_max(p_duration integer)
returns integer language sql immutable set search_path = '' as $$
  select least(216, ceil(greatest(coalesce(p_duration, 60), 1) * 1000.0 / 500.0)::integer);
$$;

create or replace function public.normalize_tokyo_play()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if auth.uid() is null or new.user_id <> auth.uid() then
    raise exception 'invalid user' using errcode = '42501';
  end if;
  new.region := 'tokyo';
  new.mode := 'all';
  new.rank_mode := 'tokyo:all';
  new.duration_sec := case when new.duration_sec in (60,120,300) then new.duration_sec else 60 end;
  new.theoretical_max := public.tokyo_theoretical_max(new.duration_sec);
  new.score := greatest(0, least(new.score, new.theoretical_max));
  return new;
end;
$$;

drop trigger if exists normalize_tokyo_play_trigger on public.plays;
create trigger normalize_tokyo_play_trigger before insert or update on public.plays
for each row execute function public.normalize_tokyo_play();

revoke all on function public.normalize_tokyo_play() from public;

drop function if exists public.all_time_ranking_by_duration(text, integer, integer);
create function public.all_time_ranking_by_duration(
  p_mode text,
  p_duration integer,
  p_limit integer default 100
)
returns table (
  rank bigint,
  user_id uuid,
  nickname text,
  theme_line text,
  best_score bigint,
  theoretical_max bigint,
  record_points numeric,
  percentile_bonus numeric,
  adjusted_score numeric
)
language sql stable security definer set search_path = '' as $$
  with best as (
    select p.user_id, max(p.score)::bigint as best_score
    from public.plays p
    where p.rank_mode = 'tokyo:all'
      and p.duration_sec = case when p_duration in (60,120,300) then p_duration else 60 end
    group by p.user_id
  ), calculated as (
    select b.user_id, b.best_score,
      public.tokyo_theoretical_max(p_duration)::bigint as theoretical_max,
      round((70 * sqrt(b.best_score::numeric / public.tokyo_theoretical_max(p_duration)))::numeric, 1) as record_points,
      count(*) over ()::bigint as participant_count,
      rank() over (order by b.best_score desc)::bigint as score_rank
    from best b
  ), scored as (
    select c.*,
      round((case when c.participant_count <= 1 then 30
        else 30 * (c.participant_count - c.score_rank)::numeric / (c.participant_count - 1) end)::numeric, 1) as percentile_bonus
    from calculated c
  ), ordered as (
    select row_number() over (
      order by (s.record_points + s.percentile_bonus) desc, s.best_score desc, s.user_id
    )::bigint as final_rank, s.*
    from scored s
  )
  select o.final_rank, o.user_id,
    coalesce(pr.nickname, '匿名プレイヤー')::text,
    coalesce(pr.theme_line, 'G')::text,
    o.best_score, o.theoretical_max, o.record_points, o.percentile_bonus,
    round((o.record_points + o.percentile_bonus)::numeric, 1) as adjusted_score
  from ordered o
  left join public.profiles pr on pr.id = o.user_id
  where o.final_rank <= least(greatest(coalesce(p_limit, 100), 1), 100)
  order by o.final_rank;
$$;

revoke all on function public.all_time_ranking_by_duration(text, integer, integer) from public;
grant execute on function public.all_time_ranking_by_duration(text, integer, integer) to anon, authenticated;
grant select, insert on public.profiles to authenticated;
grant update (nickname, theme_line, updated_at) on public.profiles to authenticated;
grant select, insert on public.plays to authenticated;
grant usage, select on sequence public.plays_id_seq to authenticated;


-- Fresh database: multiplayer room table for the Tokyo edition.
create table if not exists public.rooms (
  code text primary key check (code ~ '^[A-Z2-9]{4,8}$'),
  host_id text not null,
  host_name text not null check (char_length(host_name) between 1 and 40),
  region text not null default 'tokyo' check (region = 'tokyo'),
  mode text not null default 'all' check (mode in ('all', 'custom')),
  custom_lines text not null default '' check (
    (mode = 'all' and custom_lines = '') or
    (mode = 'custom' and custom_lines ~ '^(G|M|H|T|C|Y|Z|N|F|A|I|S|E)(,(G|M|H|T|C|Y|Z|N|F|A|I|S|E))*$')
  ),
  duration_sec integer not null default 60 check (duration_sec in (60, 120, 300)),
  play_mode text not null default 'timed' check (play_mode = 'timed'),
  status text not null default 'waiting' check (status in ('waiting', 'playing', 'ended')),
  room_title text not null default '東京メトロ対戦ルーム' check (char_length(room_title) between 2 and 30),
  is_public boolean not null default true,
  member_count integer not null default 1 check (member_count between 1 and 32),
  host_revision bigint not null default 0,
  host_changed_at timestamptz not null default now(),
  last_active_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- 이미 초기 스키마를 적용한 개발 DB도 커스텀 모드를 받을 수 있게 제약을 갱신한다.
alter table public.rooms drop constraint if exists rooms_mode_check;
alter table public.rooms add constraint rooms_mode_check check (mode in ('all', 'custom'));
alter table public.rooms drop constraint if exists rooms_custom_lines_check;
alter table public.rooms add constraint rooms_custom_lines_check check (
  (mode = 'all' and custom_lines = '') or
  (mode = 'custom' and custom_lines ~ '^(G|M|H|T|C|Y|Z|N|F|A|I|S|E)(,(G|M|H|T|C|Y|Z|N|F|A|I|S|E))*$')
);

create index if not exists rooms_created_idx on public.rooms (created_at);
create index if not exists rooms_public_lobby_idx on public.rooms (last_active_at desc)
  where is_public and status = 'waiting';

alter table public.rooms enable row level security;
drop policy if exists rooms_select_public on public.rooms;
create policy rooms_select_public on public.rooms for select using (is_public = true);


-- ============================================================
-- 대전 모드: 서버 권위형 방장/방 설정 마이그레이션
--
-- 적용 순서
--   1. 새 프로젝트라면 versus-step1-rooms.sql 실행 후 이 파일 실행
--   2. 공개방/채팅은 이어서 versus-public-rooms-chat.sql 실행
--
-- 온라인 참가자 목록은 Supabase Realtime Presence가 담당한다.
-- 이 SQL은 영속 상태(방장, 설정, 방 상태)의 변경만 원자적 RPC로 제한한다.
-- 여러 번 실행해도 안전하도록 작성되어 있다.
-- ============================================================

begin;

-- 기존 uuid host_id와 현재 게스트/세션 text id의 타입 불일치를 제거한다.
alter table public.rooms
  alter column host_id type text using host_id::text;

alter table public.rooms add column if not exists play_mode text not null default 'timed';
alter table public.rooms add column if not exists host_revision bigint not null default 0;
alter table public.rooms add column if not exists host_changed_at timestamptz not null default now();
alter table public.rooms add column if not exists updated_at timestamptz not null default now();

update public.rooms
   set duration_sec = 60
 where duration_sec not in (60, 120, 300);
alter table public.rooms alter column duration_sec set default 60;
alter table public.rooms drop constraint if exists rooms_duration_sec_check;
alter table public.rooms add constraint rooms_duration_sec_check
  check (duration_sec in (60, 120, 300));

update public.rooms set play_mode = 'timed' where play_mode <> 'timed';
alter table public.rooms drop constraint if exists rooms_play_mode_check;
alter table public.rooms add constraint rooms_play_mode_check
  check (play_mode = 'timed');

create or replace function public.room_create(
  p_code text,
  p_host text,
  p_host_name text,
  p_region text
)
returns public.rooms
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_room public.rooms;
begin
  if p_code !~ '^[A-Z2-9]{4,8}$' then
    raise exception 'invalid room code' using errcode = '22023';
  end if;
  if coalesce(length(p_host), 0) < 3 or length(p_host) > 128 then
    raise exception 'invalid player id' using errcode = '22023';
  end if;
  if coalesce(length(trim(p_host_name)), 0) < 1 or length(p_host_name) > 40 then
    raise exception 'invalid player name' using errcode = '22023';
  end if;
  if p_region <> 'tokyo' then
    raise exception 'invalid region' using errcode = '22023';
  end if;

  insert into public.rooms (
    code, host_id, host_name, region, mode, duration_sec, status,
    play_mode, host_revision, host_changed_at, updated_at
  ) values (
    p_code, p_host, trim(p_host_name), 'tokyo', 'all', 60, 'waiting',
    'timed', 0, now(), now()
  )
  returning * into v_room;

  return v_room;
end;
$$;

create or replace function public.room_update_settings(
  p_room text,
  p_host text,
  p_region text,
  p_mode text,
  p_custom_lines text,
  p_duration integer,
  p_play_mode text
)
returns public.rooms
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_room public.rooms;
  v_custom text[];
  v_normalized text;
begin
  if p_region <> 'tokyo'
     or p_mode not in ('all', 'custom')
     or p_play_mode <> 'timed'
     or p_duration not in (60, 120, 300) then
    raise exception 'invalid room settings' using errcode = '22023';
  end if;

  if p_mode = 'all' then
    if coalesce(p_custom_lines, '') <> '' then
      raise exception 'all mode cannot include custom lines' using errcode = '22023';
    end if;
    v_normalized := '';
  else
    v_custom := string_to_array(coalesce(p_custom_lines, ''), ',');
    if coalesce(array_length(v_custom, 1), 0) not between 1 and 13
       or not (v_custom <@ array['G','M','H','T','C','Y','Z','N','F','A','I','S','E']::text[])
       or (select count(distinct item) from unnest(v_custom) item) <> array_length(v_custom, 1) then
      raise exception 'invalid custom lines' using errcode = '22023';
    end if;
    v_normalized := array_to_string(v_custom, ',');
  end if;

  update public.rooms
     set region = 'tokyo',
         mode = p_mode,
         custom_lines = v_normalized,
         duration_sec = p_duration,
         play_mode = 'timed',
         updated_at = now()
   where code = p_room
     and host_id = p_host
  returning * into v_room;

  if not found then
    raise exception 'only the current host can update settings' using errcode = '42501';
  end if;
  return v_room;
end;
$$;

create or replace function public.room_set_status(
  p_room text,
  p_host text,
  p_status text
)
returns public.rooms
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_room public.rooms;
begin
  if p_status not in ('waiting', 'playing', 'ended') then
    raise exception 'invalid room status' using errcode = '22023';
  end if;

  update public.rooms
     set status = p_status,
         updated_at = now()
   where code = p_room
     and host_id = p_host
  returning * into v_room;

  if not found then
    raise exception 'only the current host can change room status' using errcode = '42501';
  end if;
  return v_room;
end;
$$;

-- 수동 위임: DB의 현재 방장이 호출자가 알고 있는 방장과 같을 때만 성공한다.
create or replace function public.room_transfer_host(
  p_room text,
  p_current_host text,
  p_new_host text,
  p_new_host_name text
)
returns public.rooms
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_room public.rooms;
begin
  if coalesce(length(p_new_host), 0) < 3 or length(p_new_host) > 128
     or coalesce(length(trim(p_new_host_name)), 0) < 1
     or length(p_new_host_name) > 40 then
    raise exception 'invalid new host' using errcode = '22023';
  end if;

  update public.rooms
     set host_id = p_new_host,
         host_name = trim(p_new_host_name),
         host_revision = host_revision + 1,
         host_changed_at = now(),
         updated_at = now()
   where code = p_room
     and host_id = p_current_host
  returning * into v_room;

  if not found then
    raise exception 'host changed before transfer completed' using errcode = '40001';
  end if;
  return v_room;
end;
$$;

-- 비정상 종료 후 자동 승계: expected_host 비교가 CAS 역할을 해 동시 요청 중 하나만 이긴다.
-- 권한 오류 대신 null을 반환해 패자는 최신 room 행을 다시 읽도록 한다.
create or replace function public.room_claim_host(
  p_room text,
  p_expected_host text,
  p_claimant text,
  p_claimant_name text
)
returns public.rooms
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_room public.rooms;
begin
  if coalesce(length(p_claimant), 0) < 3 or length(p_claimant) > 128
     or coalesce(length(trim(p_claimant_name)), 0) < 1
     or length(p_claimant_name) > 40 then
    raise exception 'invalid host claimant' using errcode = '22023';
  end if;

  update public.rooms
     set host_id = p_claimant,
         host_name = trim(p_claimant_name),
         host_revision = host_revision + 1,
         host_changed_at = now(),
         updated_at = now()
   where code = p_room
     and host_id is not distinct from p_expected_host
  returning * into v_room;

  return v_room;
end;
$$;

create or replace function public.room_delete(
  p_room text,
  p_host text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.rooms
   where code = p_room
     and host_id = p_host;
  return found;
end;
$$;

-- 브라우저의 직접 INSERT/UPDATE/DELETE 경로를 닫고 위 RPC만 공개한다.
drop policy if exists "rooms_insert_all" on public.rooms;
drop policy if exists "rooms_update_all" on public.rooms;
drop policy if exists "rooms_delete_all" on public.rooms;

revoke insert, update, delete on public.rooms from anon, authenticated;
grant select on public.rooms to anon, authenticated;

revoke all on function public.room_create(text, text, text, text) from public;
revoke all on function public.room_update_settings(text, text, text, text, text, integer, text) from public;
revoke all on function public.room_set_status(text, text, text) from public;
revoke all on function public.room_transfer_host(text, text, text, text) from public;
revoke all on function public.room_claim_host(text, text, text, text) from public;
revoke all on function public.room_delete(text, text) from public;

grant execute on function public.room_create(text, text, text, text) to anon, authenticated;
grant execute on function public.room_update_settings(text, text, text, text, text, integer, text) to anon, authenticated;
grant execute on function public.room_set_status(text, text, text) to anon, authenticated;
grant execute on function public.room_transfer_host(text, text, text, text) to anon, authenticated;
grant execute on function public.room_claim_host(text, text, text, text) to anon, authenticated;
grant execute on function public.room_delete(text, text) to anon, authenticated;

-- rooms/game_states Postgres Changes 구독을 활성화한다. Presence는 publication이 필요 없다.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
        where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'rooms'
     ) then
    alter publication supabase_realtime add table public.rooms;
  end if;

  if to_regclass('public.game_states') is not null
     and exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
        where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'game_states'
     ) then
    alter publication supabase_realtime add table public.game_states;
  end if;
end;
$$;

commit;


-- ============================================================
-- 대전 모드: 공개방 목록 + 비공개방 + 영속 채팅/신고 마이그레이션
--
-- 적용 전제: versus-step1-rooms.sql, versus-multiplayer-authority.sql
-- 여러 번 실행해도 안전하다.
-- ============================================================

begin;

alter table public.rooms add column if not exists room_title text not null default '東京メトロ対戦ルーム';
alter table public.rooms add column if not exists is_public boolean not null default true;
alter table public.rooms add column if not exists member_count integer not null default 1;
alter table public.rooms add column if not exists last_active_at timestamptz not null default now();

alter table public.rooms drop constraint if exists rooms_title_length_check;
alter table public.rooms add constraint rooms_title_length_check
  check (char_length(room_title) between 2 and 30);
alter table public.rooms drop constraint if exists rooms_member_count_check;
alter table public.rooms add constraint rooms_member_count_check
  check (member_count between 1 and 32);

create index if not exists rooms_public_lobby_idx
  on public.rooms (last_active_at desc)
  where is_public and status = 'waiting';

-- 직접 테이블 조회에서는 공개방만 보인다. 비공개방은 정확한 코드를
-- room_get RPC에 전달해야만 조회할 수 있다.
alter table public.rooms enable row level security;
drop policy if exists "rooms_select_all" on public.rooms;
drop policy if exists "rooms_select_public" on public.rooms;
create policy "rooms_select_public" on public.rooms
  for select using (is_public = true);

create or replace function public.versus_has_blocked_terms(p_text text)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select regexp_replace(lower(coalesce(p_text, '')), '[^0-9a-zぁ-んァ-ヶ一-龠々]', '', 'g')
         ~ '(しね|死ね|ころす|殺す|くそ|クソ|ばか|バカ|あほ|アホ|きもい|うざい|ちんこ|まんこ|fuck|shit|bitch)';
$$;

revoke all on function public.versus_has_blocked_terms(text) from public;

create or replace function public.room_create_v2(
  p_code text,
  p_host text,
  p_host_name text,
  p_region text,
  p_room_title text,
  p_is_public boolean
)
returns public.rooms
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_room public.rooms;
  v_title text := regexp_replace(trim(coalesce(p_room_title, '')), '\s+', ' ', 'g');
begin
  if p_code !~ '^[A-Z2-9]{4,8}$' then
    raise exception 'invalid room code' using errcode = '22023';
  end if;
  if coalesce(length(p_host), 0) < 3 or length(p_host) > 128 then
    raise exception 'invalid player id' using errcode = '22023';
  end if;
  if coalesce(length(trim(p_host_name)), 0) < 1 or length(p_host_name) > 40 then
    raise exception 'invalid player name' using errcode = '22023';
  end if;
  if p_region <> 'tokyo' then
    raise exception 'invalid region' using errcode = '22023';
  end if;
  if char_length(v_title) not between 2 and 30 or public.versus_has_blocked_terms(v_title) then
    raise exception 'invalid or blocked room title' using errcode = '22023';
  end if;

  insert into public.rooms (
    code, host_id, host_name, region, mode, duration_sec, status,
    play_mode, host_revision, host_changed_at, updated_at,
    room_title, is_public, member_count, last_active_at
  ) values (
    p_code, p_host, trim(p_host_name), 'tokyo', 'all', 60, 'waiting',
    'timed', 0, now(), now(), v_title, coalesce(p_is_public, true), 1, now()
  )
  returning * into v_room;

  return v_room;
end;
$$;

create or replace function public.room_get(p_code text)
returns public.rooms
language sql
security definer
set search_path = ''
stable
as $$
  select rooms.*
    from public.rooms
   where rooms.code = upper(trim(p_code))
     and upper(trim(p_code)) ~ '^[A-Z2-9]{4,8}$'
   limit 1;
$$;

-- 반환 컬럼(play_mode)이 추가되므로 기존 시그니처를 먼저 제거한다.
drop function if exists public.room_list_public(integer);
create function public.room_list_public(p_limit integer default 30)
returns table (
  code text,
  room_title text,
  host_name text,
  region text,
  mode text,
  play_mode text,
  duration_sec integer,
  status text,
  member_count integer,
  created_at timestamptz
)
language sql
security definer
set search_path = ''
stable
as $$
  select rooms.code, rooms.room_title, rooms.host_name, rooms.region, rooms.mode,
         rooms.play_mode, rooms.duration_sec, rooms.status, rooms.member_count, rooms.created_at
    from public.rooms
   where rooms.is_public = true
     and rooms.status = 'waiting'
     and rooms.last_active_at >= now() - interval '90 seconds'
   order by rooms.last_active_at desc, rooms.created_at desc
   limit greatest(1, least(coalesce(p_limit, 30), 50));
$$;

create or replace function public.room_heartbeat(
  p_room text,
  p_host text,
  p_member_count integer
)
returns public.rooms
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_room public.rooms;
begin
  if p_member_count not between 1 and 32 then
    raise exception 'invalid member count' using errcode = '22023';
  end if;
  update public.rooms
     set member_count = p_member_count,
         last_active_at = now(),
         updated_at = now()
   where code = upper(trim(p_room))
     and host_id = p_host
  returning * into v_room;
  return v_room;
end;
$$;

create table if not exists public.room_messages (
  id bigint generated by default as identity primary key,
  room_code text not null references public.rooms(code) on delete cascade,
  player_id text not null,
  player_name text not null,
  body text not null,
  report_count integer not null default 0,
  is_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  constraint room_messages_player_id_check check (char_length(player_id) between 3 and 128),
  constraint room_messages_player_name_check check (char_length(player_name) between 1 and 40),
  constraint room_messages_body_check check (char_length(body) between 1 and 200),
  constraint room_messages_report_count_check check (report_count >= 0)
);

create index if not exists room_messages_room_created_idx
  on public.room_messages (room_code, created_at desc);

create table if not exists public.room_message_reports (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.room_messages(id) on delete cascade,
  room_code text not null references public.rooms(code) on delete cascade,
  reporter_id text not null,
  reason text not null default '不適切な内容',
  created_at timestamptz not null default now(),
  unique (message_id, reporter_id),
  constraint room_message_reports_reason_check check (char_length(reason) between 1 and 80)
);

alter table public.room_messages enable row level security;
alter table public.room_message_reports enable row level security;

-- 채팅 테이블 직접 접근은 모두 닫고, 방 코드를 받는 아래 RPC로만 읽고 쓴다.
revoke all on public.room_messages from anon, authenticated;
revoke all on public.room_message_reports from anon, authenticated;

create or replace function public.room_chat_history(
  p_room text,
  p_limit integer default 80
)
returns table (
  id bigint,
  player_id text,
  player_name text,
  body text,
  report_count integer,
  is_hidden boolean,
  created_at timestamptz
)
language sql
security definer
set search_path = ''
stable
as $$
  select history.id, history.player_id, history.player_name, history.body,
         history.report_count, history.is_hidden, history.created_at
    from (
      select messages.*
        from public.room_messages messages
       where messages.room_code = upper(trim(p_room))
         and messages.is_hidden = false
       order by messages.id desc
       limit greatest(1, least(coalesce(p_limit, 80), 100))
    ) history
   order by history.id;
$$;

create or replace function public.room_send_message(
  p_room text,
  p_player text,
  p_player_name text,
  p_body text
)
returns public.room_messages
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_message public.room_messages;
  v_body text := regexp_replace(trim(coalesce(p_body, '')), '\s+', ' ', 'g');
  v_compact text;
  v_recent_count integer;
begin
  if not exists (select 1 from public.rooms where code = upper(trim(p_room)) and status <> 'ended') then
    raise exception 'room not found or closed' using errcode = '22023';
  end if;
  if char_length(coalesce(p_player, '')) not between 3 and 128
     or char_length(trim(coalesce(p_player_name, ''))) not between 1 and 40
     or char_length(v_body) not between 1 and 200 then
    raise exception 'invalid chat message' using errcode = '22023';
  end if;
  v_compact := regexp_replace(lower(v_body), '[^0-9a-zぁ-んァ-ヶ一-龠々]', '', 'g');
  if public.versus_has_blocked_terms(v_body) or v_compact ~ '(.)\1{9,}' then
    raise exception 'blocked chat message' using errcode = '22023';
  end if;
  if (select count(*) from regexp_matches(lower(v_body), 'https?://', 'g')) > 1 then
    raise exception 'too many links' using errcode = '22023';
  end if;

  select count(*) into v_recent_count
    from public.room_messages
   where room_code = upper(trim(p_room))
     and player_id = p_player
     and created_at >= now() - interval '10 seconds';
  if v_recent_count >= 6 then
    raise exception 'chat rate limit exceeded' using errcode = 'P0001';
  end if;
  if exists (
    select 1 from public.room_messages
     where room_code = upper(trim(p_room)) and player_id = p_player
       and body = v_body and created_at >= now() - interval '30 seconds'
  ) then
    raise exception 'duplicate chat message' using errcode = 'P0001';
  end if;

  insert into public.room_messages (room_code, player_id, player_name, body)
  values (upper(trim(p_room)), p_player, trim(p_player_name), v_body)
  returning * into v_message;
  return v_message;
end;
$$;

create or replace function public.room_report_message(
  p_room text,
  p_message bigint,
  p_reporter text,
  p_reason text default '不適切な内容'
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_inserted integer := 0;
  v_reason text := left(trim(coalesce(p_reason, '不適切な内容')), 80);
  v_reporter_identity text := coalesce(auth.uid()::text, p_reporter);
begin
  if char_length(coalesce(p_reporter, '')) not between 3 and 128
     or char_length(v_reason) < 1 then
    raise exception 'invalid report' using errcode = '22023';
  end if;
  if not exists (
    select 1 from public.room_messages
     where id = p_message and room_code = upper(trim(p_room))
       and player_id <> p_reporter
  ) then
    raise exception 'message not found or self report' using errcode = '22023';
  end if;

  insert into public.room_message_reports (message_id, room_code, reporter_id, reason)
  values (p_message, upper(trim(p_room)), v_reporter_identity, v_reason)
  on conflict (message_id, reporter_id) do nothing;
  get diagnostics v_inserted = row_count;
  if v_inserted = 0 then return false; end if;

  update public.room_messages messages
     set report_count = reports.count,
         is_hidden = reports.count >= 3
    from (
      select count(*)::integer as count
        from public.room_message_reports
       where message_id = p_message
    ) reports
   where messages.id = p_message;
  return true;
end;
$$;

-- Supabase Cron에서 하루 한 번 호출할 수 있는 정리 함수.
-- 24시간 이상 heartbeat가 없는 방과 연결된 채팅/신고가 CASCADE로 함께 삭제된다.
create or replace function public.cleanup_stale_versus_rooms()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_deleted integer;
begin
  delete from public.rooms
   where last_active_at < now() - interval '24 hours';
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

revoke all on function public.room_create_v2(text, text, text, text, text, boolean) from public;
revoke all on function public.room_get(text) from public;
revoke all on function public.room_list_public(integer) from public;
revoke all on function public.room_heartbeat(text, text, integer) from public;
revoke all on function public.room_chat_history(text, integer) from public;
revoke all on function public.room_send_message(text, text, text, text) from public;
revoke all on function public.room_report_message(text, bigint, text, text) from public;
revoke all on function public.cleanup_stale_versus_rooms() from public;

grant execute on function public.room_create_v2(text, text, text, text, text, boolean) to anon, authenticated;
grant execute on function public.room_get(text) to anon, authenticated;
grant execute on function public.room_list_public(integer) to anon, authenticated;
grant execute on function public.room_heartbeat(text, text, integer) to anon, authenticated;
grant execute on function public.room_chat_history(text, integer) to anon, authenticated;
grant execute on function public.room_send_message(text, text, text, text) to anon, authenticated;
grant execute on function public.room_report_message(text, bigint, text, text) to anon, authenticated;

notify pgrst, 'reload schema';

commit;


-- Authoritative multiplayer game clock and scores.
create table if not exists public.game_states (
  room_code text primary key references public.rooms(code) on delete cascade,
  phase text not null default 'lobby' check (phase in ('lobby','countdown','playing','reveal','ended')),
  rev bigint not null default 0,
  q_order text[] not null default '{}',
  question_index integer not null default -1,
  region text not null default 'tokyo' check (region = 'tokyo'),
  line_ids text[] not null default '{}',
  duration_sec integer not null default 60 check (duration_sec in (60,120,300)),
  play_at timestamptz,
  q_ends_at timestamptz,
  game_ends_at timestamptz,
  reveal_until timestamptz,
  winner_id text,
  winner_name text,
  scores jsonb not null default '{}',
  names jsonb not null default '{}',
  updated_at timestamptz not null default now()
);

alter table public.game_states enable row level security;
drop policy if exists game_states_read_all on public.game_states;
revoke all on public.game_states from anon, authenticated;

create or replace function public.vs_start(
  p_room text, p_host text, p_region text, p_line_ids text[], p_order text[],
  p_duration integer, p_names jsonb
)
returns public.game_states language plpgsql security definer set search_path = '' as $$
declare
  v_state public.game_states;
  v_play_at timestamptz := clock_timestamp() + interval '3 seconds';
  v_allowed constant text[] := array['G','M','H','T','C','Y','Z','N','F','A','I','S','E']::text[];
begin
  if p_region <> 'tokyo' or p_duration not in (60,120,300)
     or coalesce(array_length(p_line_ids, 1), 0) not between 1 and 13
     or not (p_line_ids <@ v_allowed)
     or (select count(distinct item) from unnest(p_line_ids) item) <> array_length(p_line_ids, 1)
     or coalesce(array_length(p_order, 1), 0) < 1 then
    raise exception 'invalid game settings' using errcode = '22023';
  end if;
  if not exists (select 1 from public.rooms where code = p_room and host_id = p_host and status <> 'ended') then
    raise exception 'only the current host can start' using errcode = '42501';
  end if;
  insert into public.game_states (
    room_code, phase, rev, q_order, question_index, region, line_ids, duration_sec,
    play_at, q_ends_at, game_ends_at, reveal_until, winner_id, winner_name, scores, names, updated_at
  ) values (
    p_room, 'countdown', 1, p_order, 0, 'tokyo', p_line_ids, p_duration,
    v_play_at, v_play_at + interval '10 seconds', v_play_at + make_interval(secs => p_duration),
    null, null, null, '{}'::jsonb, coalesce(p_names, '{}'::jsonb), clock_timestamp()
  ) on conflict (room_code) do update set
    phase = 'countdown', rev = public.game_states.rev + 1, q_order = excluded.q_order,
    question_index = 0, region = 'tokyo', line_ids = excluded.line_ids,
    duration_sec = excluded.duration_sec, play_at = excluded.play_at,
    q_ends_at = excluded.q_ends_at, game_ends_at = excluded.game_ends_at,
    reveal_until = null, winner_id = null, winner_name = null,
    scores = '{}'::jsonb, names = excluded.names, updated_at = clock_timestamp()
  returning * into v_state;
  return v_state;
end;
$$;

create or replace function public.vs_sync(p_room text)
returns public.game_states language sql stable security definer set search_path = '' as $$
  select state.* from public.game_states state where state.room_code = upper(trim(p_room)) limit 1;
$$;

create or replace function public.vs_join(
  p_room text, p_player_id text, p_name text, p_theme text
)
returns public.game_states language plpgsql security definer set search_path = '' as $$
declare v_state public.game_states;
begin
  if char_length(coalesce(p_player_id,'')) not between 3 and 128
     or char_length(trim(coalesce(p_name,''))) not between 1 and 40 then
    raise exception 'invalid player' using errcode = '22023';
  end if;
  update public.game_states set
    names = jsonb_set(coalesce(names, '{}'::jsonb), array[p_player_id],
      jsonb_build_object('name', trim(p_name), 'themeLine', nullif(p_theme,'')), true),
    rev = rev + 1, updated_at = clock_timestamp()
  where room_code = upper(trim(p_room)) returning * into v_state;
  return v_state;
end;
$$;

create or replace function public.vs_claim(
  p_room text, p_index integer, p_player_id text, p_player_name text
)
returns public.game_states language plpgsql security definer set search_path = '' as $$
declare v_state public.game_states; v_score integer;
begin
  select * into v_state from public.game_states where room_code = upper(trim(p_room)) for update;
  if not found then return null; end if;
  if v_state.phase <> 'playing' or v_state.question_index <> p_index
     or clock_timestamp() >= v_state.q_ends_at or clock_timestamp() >= v_state.game_ends_at then
    return v_state;
  end if;
  v_score := coalesce((v_state.scores ->> p_player_id)::integer, 0) + 1;
  update public.game_states set
    phase = 'reveal', winner_id = p_player_id, winner_name = left(trim(p_player_name), 40),
    scores = jsonb_set(coalesce(scores, '{}'::jsonb), array[p_player_id], to_jsonb(v_score), true),
    names = jsonb_set(coalesce(names, '{}'::jsonb), array[p_player_id],
      coalesce(names -> p_player_id, jsonb_build_object('name', left(trim(p_player_name),40), 'themeLine', null)), true),
    reveal_until = least(game_ends_at, clock_timestamp() + interval '500 milliseconds'),
    rev = rev + 1, updated_at = clock_timestamp()
  where room_code = v_state.room_code returning * into v_state;
  return v_state;
end;
$$;

create or replace function public.vs_tick(p_room text)
returns public.game_states language plpgsql security definer set search_path = '' as $$
declare v_state public.game_states; v_now timestamptz := clock_timestamp(); v_next integer;
begin
  select * into v_state from public.game_states where room_code = upper(trim(p_room)) for update;
  if not found then return null; end if;
  if v_state.phase in ('ended','lobby') then return v_state; end if;
  if v_state.game_ends_at is not null and v_now >= v_state.game_ends_at then
    update public.game_states set phase='ended', rev=rev+1, updated_at=v_now
      where room_code=v_state.room_code returning * into v_state;
    return v_state;
  end if;
  if v_state.phase = 'countdown' and v_now >= v_state.play_at then
    update public.game_states set phase='playing', q_ends_at=least(game_ends_at,v_now+interval '10 seconds'),
      rev=rev+1, updated_at=v_now where room_code=v_state.room_code returning * into v_state;
  elsif v_state.phase = 'playing' and v_now >= v_state.q_ends_at then
    update public.game_states set phase='reveal', winner_id=null, winner_name=null,
      reveal_until=least(game_ends_at,v_now+interval '500 milliseconds'), rev=rev+1, updated_at=v_now
      where room_code=v_state.room_code returning * into v_state;
  elsif v_state.phase = 'reveal' and v_now >= v_state.reveal_until then
    v_next := v_state.question_index + 1;
    if v_next >= coalesce(array_length(v_state.q_order,1),0) then
      update public.game_states set phase='ended', rev=rev+1, updated_at=v_now
        where room_code=v_state.room_code returning * into v_state;
    else
      update public.game_states set phase='playing', question_index=v_next, winner_id=null, winner_name=null,
        reveal_until=null, q_ends_at=least(game_ends_at,v_now+interval '10 seconds'), rev=rev+1, updated_at=v_now
        where room_code=v_state.room_code returning * into v_state;
    end if;
  end if;
  return v_state;
end;
$$;

create or replace function public.vs_end(p_room text)
returns public.game_states language plpgsql security definer set search_path = '' as $$
declare v_state public.game_states;
begin
  select * into v_state from public.game_states where room_code=upper(trim(p_room)) for update;
  if not found or v_state.phase in ('ended','lobby') then return v_state; end if;
  -- The browser may request completion, but only the database clock may end a match.
  if v_state.game_ends_at is null or clock_timestamp() < v_state.game_ends_at then return v_state; end if;
  update public.game_states set phase='ended', rev=rev+1, updated_at=clock_timestamp()
    where room_code=v_state.room_code returning * into v_state;
  return v_state;
end;
$$;

create or replace function public.vs_lobby(p_room text, p_host text)
returns public.game_states language plpgsql security definer set search_path = '' as $$
declare v_state public.game_states;
begin
  if not exists (select 1 from public.rooms where code=upper(trim(p_room)) and host_id=p_host) then
    raise exception 'only the current host can return to lobby' using errcode='42501';
  end if;
  update public.game_states set phase='lobby', rev=rev+1, q_order='{}', question_index=-1,
    play_at=null, q_ends_at=null, game_ends_at=null, reveal_until=null, winner_id=null, winner_name=null,
    scores='{}', updated_at=clock_timestamp() where room_code=upper(trim(p_room)) returning * into v_state;
  return v_state;
end;
$$;

revoke all on function public.vs_start(text,text,text,text[],text[],integer,jsonb) from public;
revoke all on function public.vs_sync(text) from public;
revoke all on function public.vs_join(text,text,text,text) from public;
revoke all on function public.vs_claim(text,integer,text,text) from public;
revoke all on function public.vs_tick(text) from public;
revoke all on function public.vs_end(text) from public;
revoke all on function public.vs_lobby(text,text) from public;
grant execute on function public.vs_start(text,text,text,text[],text[],integer,jsonb) to anon, authenticated;
grant execute on function public.vs_sync(text) to anon, authenticated;
grant execute on function public.vs_join(text,text,text,text) to anon, authenticated;
grant execute on function public.vs_claim(text,integer,text,text) to anon, authenticated;
grant execute on function public.vs_tick(text) to anon, authenticated;
grant execute on function public.vs_end(text) to anon, authenticated;
grant execute on function public.vs_lobby(text,text) to anon, authenticated;

notify pgrst, 'reload schema';

